global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'csvserver-monitor'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - csvserver:9300
